# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort imports pynisher
        files: pynisher/.*
        args: [--check]

      - id: isort
        name: isort imports test
        files: test/.*
        args: [--check]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black formatter pynisher
        files: pynisher/.*
        args: [--check]

      - id: black
        name: black formatter test
        files: test/.*
        args: [--check]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: pynisher/.*
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        name: mypy pynisher
        files: pynisher/.*

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 pynisher
        files: pynisher/.*

      - id: flake8
        name: flake8 test
        files: test/.*
